openapi: "3.0.0"
info:
  version: 1.0.0
  title: SHOP API
  description: API of Events App, a social media platform for hosting and organizing in-person and virtual activities, gatherings, and events for people and communities of similar interests, hobbies, and professions. It.
  license:
    name: MIT
  contact:  
    name: API Creator
    url: http://www.andresjpulido.com/
    email: andresjpulido@gmail.com
servers:
  - url: http://shop.swagger.io/v1
  - url: http://localhost/v1
tags:
  - name: users
paths:
  /orders:
    $ref: "./resources/orders.yaml"
  /orders/{id}:
    $ref: "./resources/orders2.yaml"
   
  
