const mykey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDS7gOeiyISHIKwwBTVXJI/7oPT
MMbo8zuWMkKx2cKRNgru1e2ttw83IIgk03Q7F6xNTqWBh22CyFVgiB2MUjqg/GGz
JrSpDhTzE5PI0JlV8V7MNhARbk8wODJeck8kIKd3oRmr8tQkEvtppJTSJ3YSLNZL
FeqY0BJL+uEiMvjE7wIDAQAB
-----END PUBLIC KEY-----`
export default mykey
