export const HOST = 'http://localhost:4000'


export const CUSTOMERS_URL = HOST + '/api/customers'
export const EMPLOYEES_URL = HOST + '/api/employees' 
export const GET_HOURS_URL = HOST + '/api/hours'
//export const GET_INV_URL= HOST + '/api/inventory'
export const GET_INV_URL= HOST + '/api/inventoryproducts'
export const GET_MOV_URL = HOST + '/api/movements'
export const GET_OPERATION_URL = HOST + '/api/operations'
export const GET_SIZE_URL = HOST + '/api/sizes'
export const GET_PARAMETER_URL = HOST + '/api/parameters'
export const HOUR_URL = HOST + '/api/hours'
export const IMAGES_URL = HOST + '/api/images'
export const LOCATIONS_URL = HOST + '/api/locations'
export const NEW_MOV_URL = HOST + '/api/movement'
export const ORDER_URL = HOST + '/api/orders'
export const PAYSLIPS_URL = HOST + '/api/payslips'
export const PAYSLIPPDF_URL = HOST + '/api/payslippdf'
export const PRODUCTTYPE_URL = HOST + '/api/producttypes'
export const PRODUCTS_URL = HOST +   '/api/products'
export const PRODUCTION_REPORT_URL = HOST + '/api/productionreport'
export const SIGNIN_URL = HOST + '/api/signIn'
export const STATUS_URL = HOST + '/api/status'
export const REP_MOV_URL = HOST + '/api/movement/report'
export const RESOURCE_URL = HOST + '/api/resources'
export const ROL_URL = HOST + '/api/roles'

export const USER_URL = HOST + '/api/users'
export const NOTE_URL = HOST + '/api/notes'
export const DEPOSIT_URL = HOST + '/api/deposits'